stages:
  - build
  - tests
  - history_copy
  - reports
  - make_report
build:
  image:
    name: registry.sbermarket.tech/docker/proxy/kaniko-project/executor:debug-v1.0.0
    entrypoint: [""]
  stage: build
  tags:
    - docker
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - echo $CI_REGISTRY
    - echo $IMAGE
    - /kaniko/executor
      --cache=true
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE

CustomSuiteTestRun:
  when: manual
  image: gradle:jdk11
  stage: tests
  services:
    - selenium/standalone-chrome
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - echo $QASE
    - echo $BROWSER
    - cd web-tests
    - ./gradlew clean $TEST_SET -Penv=$P_ENV -Pbrowser=$BROWSER -Pqase=$QASE
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
    expire_in: 1 week

tests:apiv2:
  when: manual
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - echo $BROWSER
    - cd web-tests
    - ./gradlew clean apiV2Regress -Penv=$P_ENV -Pqase=true
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
    expire_in: 1 week

tests:apiShopper:
  when: manual
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - echo $BROWSER
    - cd web-tests
    - ./gradlew build apiShopperRegress -Penv=$P_ENV -Pqase=true
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
    expire_in: 1 week

tests:apiZonesProductionOnly:
  when: manual
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - echo $BROWSER
    - cd web-tests
    - ./gradlew build apiZones -Penv=$P_ENV -Pqase=true
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
    expire_in: 1 week

tests:UiSmoke:
  when: manual
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - echo $BROWSER
    - cd web-tests
    - - ./gradlew build sberUiSmoke -Penv=$P_ENV -Pbrowser=$BROWSER -Pqase=true
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
    expire_in: 1 week

tests:debug:
  when: manual
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $REPORT
    - echo $REPORT_URL
    - echo $P_ENV
    - cd web-tests
    - ./gradlew build debug
    - bash ./report.sh /build/allure-results http://allurerest.matthew.keenetic.link default
  tags:
    - k8s-stage

tests:debugV2:
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - cd web-tests
    - ./gradlew build debug
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
    expire_in: 1 day

history:
  stage: history_copy
  tags:
    - docker
  image: storytel/alpine-bash-curl
  script:
    - 'curl --location --output artifacts.zip "https://gitlab.sbermarket.tech/api/v4/projects/121/jobs/artifacts/master/download?job=pages&job_token=$CI_JOB_TOKEN"'
    - apk add unzip
    - unzip artifacts.zip
    - chmod -R 777 public
    - cp -r ./public/history ./web-tests/build/allure-results
  allow_failure: true
  artifacts:
    paths:
      - ./allure-results
    expire_in: 1 day
  rules:
    - when: always

allure:
  stage: reports
  tags:
    - docker
  image: frankescobar/allure-docker-service
  script:
    - allure generate -c ./allure-results -o ./allure-report
  artifacts:
    paths:
      - ./allure-results
      - ./allure-report
    expire_in: 1 day
  rules:
    - when: always

pages:
  stage: make_report
  script:
    - mkdir public
    - mv ./allure-report/* public
  artifacts:
    paths:
      - public
  rules:
    - when: always

