include:
  - local: '/.gitlab-ci/api.yaml'
  - local: '/.gitlab-ci/shopper.yaml'
  - local: '/.gitlab-ci/grpc.yaml'
  - local: '/.gitlab-ci/ui.yaml'
  - local: '/.gitlab-ci/ui-tenant.yaml'

image: ${JDK11_GRADLE_IMAGE}

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - web-tests/.gradle

variables:
  JDK_GRADLE: 'gradle:7-jdk11'
  JDK11_GRADLE_VERSION: 'latest'
  JDK11_GRADLE_IMAGE: "${CI_REGISTRY}/qa/automag/java:${JDK11_GRADLE_VERSION}"
  RUNNER_IMAGE_REPO: "dreg.sbmt.io/library"
  RUNNER_IMAGE_NAME: "ci-tools"
  RUNNER_IMAGE_TAG: "v1.4.5"
  RUNNER_IMAGE_URL: "${RUNNER_IMAGE_REPO}/${RUNNER_IMAGE_NAME}:${RUNNER_IMAGE_TAG}"
  GIT_SUBMODULE_STRATEGY: normal
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  CI_RUN_ALL_JOBS: "true"

before_script:
  - export GRADLE_USER_HOME=$(pwd)/web-tests/.gradle
  - cd web-tests

stages:
  - build
  - tests-api
  - tests-ui
  - custom-run

.template_only_branches:
  only:
    refs:
      - branches
  except:
    refs:
      - master
      - schedules
  when: manual

.template_prod:
  only:
    refs:
      - master
    variables:
      - $PRODACTION == 'true'

.template_schedule:
  only:
    refs:
      - schedules
    variables:
      - $REGRESSION == 'true'
  when: always

.template_web:
  only:
    refs:
      - web
  when: always

.template_run_all_jobs_at_a_time_on_master:
  only:
    refs:
      - master
    variables:
      - $CI_RUN_ALL_JOBS == 'true'
  except:
    refs:
      - schedules

.template_stage:
  only:
    refs:
      - master
    variables:
      - $URL_STF != "stf-kraken.k-stage.sbermarket.tech"
  except:
    refs:
      - schedules

.template_api_tests:
  stage: tests-api
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/api/build/allure-results/
      - web-tests/api/logs/
      - web-tests/api/build/reports/tests/
    expire_in: 1 week
  allow_failure: false

.template_grpc_tests:
  stage: tests-api
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/grpc/build/allure-results/
      - web-tests/grpc/logs/
      - web-tests/grpc/build/reports/tests/
    expire_in: 1 week
  allow_failure: false

.template_ui_tests:
  resource_group: ui:$CI_COMMIT_REF_SLUG
  stage: tests-ui
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/reforged/build/allure-results/
      - web-tests/reforged/logs/
      - web-tests/reforged/build/reports/tests/
    expire_in: 1 week
  allow_failure: true

java_gradle:build:
  extends: ".template_only_branches"
  stage: build
  image: ${RUNNER_IMAGE_URL}
  tags:
    - stage-static
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker pull ${JDK_GRADLE}
    - docker tag ${JDK_GRADLE} ${JDK11_GRADLE_IMAGE}
    - docker push ${JDK11_GRADLE_IMAGE}

CustomSuiteTestRun:
  only:
    variables:
      - $TEST_API_INSTAMART == 'false' && $CI_RUN_ALL_JOBS == 'false' && $API_SHOPPER_ALONE == 'false'
  allow_failure: true
  when: manual
  stage: custom-run
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - echo $QASE
    - echo $BROWSER
    - echo $PROXY_IP
    - echo $PROXY_PORT
    - echo $PROXY_TIMEOUT
    - echo $URL_STF
    - echo $URL_SHP
    - gradle clean build $TEST_SET -Penv=$P_ENV -Pbrowser=$BROWSER -Pqase=$QASE -Purl_stf=$URL_STF -Purl_shp=$URL_SHP -Pkey=$ATST_APP_SECRET_KEY
  after_script:
    - bash ./report.sh reforged default
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/reforged/build/allure-results/
      - web-tests/reforged/logs/
      - web-tests/reforged/build/reports/tests/
    expire_in: 1 week

tests:AutoMRCheck:
  only:
    - merge_requests
  stage: tests-api
  script:
    - echo $P_ENV
    - gradle clean build AutoMRCheck -Penv=$P_ENV -Pqase=false -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - bash ./report.sh . default
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/api/build/allure-results/
      - web-tests/api/logs/
      - web-tests/api/build/reports/tests/
      - web-tests/reforged/build/allure-results/
      - web-tests/reforged/logs/
      - web-tests/reforged/build/reports/tests/
    expire_in: 1 week
  allow_failure: true

tests:Debug:
  extends: ".template_only_branches"
  stage: tests-api
  script:
    - echo $P_ENV
    - gradle clean build debug -Penv=$P_ENV -Pqase=false -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - bash ./report.sh debug
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
      - web-tests/logs/
    expire_in: 1 week

qase:actualize:
  only:
    refs:
      - schedules
    variables:
      - $ACTUALIZATION == 'true'
  stage: tests-api
  script:
    - gradle clean build qaseActualize -Pkey=$ATST_APP_SECRET_KEY
  tags:
    - k8s-stage
  allow_failure: true
