testAuto:
  when: manual
  image: gradle:jdk11
  services:
    - selenium/standalone-chrome
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    - brew cask install chromedriver
    - cd web-tests
    - ./gradlew clean sberSmoke -Penv=$P_ENV -Pbrowser=chrome allureReport
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
    expire_in: 1 week
