include:
  - local: '/.gitlab-ci/api.yaml'
  - local: '/.gitlab-ci/shopper.yaml'
  - local: '/.gitlab-ci/grpc.yaml'
  - local: '/.gitlab-ci/ui.yaml'
  - local: '/.gitlab-ci/ui-tenant.yaml'

image: gradle:jre11

variables:
  GIT_SUBMODULE_STRATEGY: normal
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  CI_RUN_ALL_JOBS: "true"

before_script:
  - cd web-tests

stages:
  - tests-api
  - tests-ui
  - custom-run

.template_actualization:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $ACTUALIZATION == "true"'
      when: always
    - when: never

.template_run_debug:
  rules:
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE != "schedule" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
    - when: never

.template_run_schedule:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $REGRESSION == "true"'
      when: always
    - when: never

.template_run_jobs_at_a_time_on_master:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $GRPC_PRODUCT_HUB_ALONE == "true" && $CI_RUN_ALL_JOBS == "false"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_RUN_ALL_JOBS == "true"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $TEST_API_SHOPPER == "true" && $CI_RUN_ALL_JOBS == "false"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $API_SHOPPER_ALONE == "true" && $CI_RUN_ALL_JOBS == "false"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $TEST_API_INSTAMART == "true" && $CI_RUN_ALL_JOBS == "false"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $TEST_UI_SMOKE == "true" && $CI_RUN_ALL_JOBS == "false"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $TEST_ADMIN_UI_SMOKE == "true" && $CI_RUN_ALL_JOBS == "false"'
      when: always
    - when: never

.template_api_tests:
  stage: tests-api
  image: $CI_REGISTRY_IMAGE
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/api/build/allure-results/
      - web-tests/api/logs/
      - web-tests/api/build/reports/tests/
    expire_in: 1 week
  allow_failure: false

.template_grpc_tests:
  stage: tests-api
  image: $CI_REGISTRY_IMAGE
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/grpc/build/allure-results/
      - web-tests/grpc/logs/
      - web-tests/grpc/build/reports/tests/
    expire_in: 1 week
  allow_failure: false

.template_ui_tests:
  resource_group: ui:$CI_COMMIT_REF_SLUG
  stage: tests-ui
  image: $CI_REGISTRY_IMAGE
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/reforged/build/allure-results/
      - web-tests/reforged/logs/
      - web-tests/reforged/build/reports/tests/
    expire_in: 1 week
  allow_failure: true

CustomSuiteTestRun:
  only:
    variables:
      - $TEST_API_INSTAMART == 'false' && $CI_RUN_ALL_JOBS == 'false' && $API_SHOPPER_ALONE == 'false'
  allow_failure: true
  when: manual
  stage: custom-run
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - echo $QASE
    - echo $BROWSER
    - echo $PROXY_IP
    - echo $PROXY_PORT
    - echo $PROXY_TIMEOUT
    - echo $URL_STF
    - echo $URL_SHP
    - gradle clean build $TEST_SET -Penv=$P_ENV -Pbrowser=$BROWSER -Pqase=$QASE -Purl_stf=$URL_STF -Purl_shp=$URL_SHP -Pkey=$ATST_APP_SECRET_KEY
  after_script:
    - bash ./report.sh reforged default
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/reforged/build/allure-results/
      - web-tests/reforged/logs/
      - web-tests/reforged/build/reports/tests/
    expire_in: 1 week

tests:AutoMRCheck:
  only:
    - merge_requests
  stage: tests-api
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - gradle clean build AutoMRCheck -Penv=$P_ENV -Pqase=false -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - bash ./report.sh . default
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/api/build/allure-results/
      - web-tests/api/logs/
      - web-tests/api/build/reports/tests/
      - web-tests/reforged/build/allure-results/
      - web-tests/reforged/logs/
      - web-tests/reforged/build/reports/tests/
    expire_in: 1 week
  allow_failure: true

tests:Debug:
  extends: ".template_run_debug"
  stage: tests-api
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - gradle clean build debug -Penv=$P_ENV -Pqase=false -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - bash ./report.sh debug
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
      - web-tests/logs/
    expire_in: 1 week

qase:actualize:
  extends:
    - ".template_actualization"
  image: $CI_REGISTRY_IMAGE
  stage: tests-api
  script:
    - gradle clean build qaseActualize -Pkey=$ATST_APP_SECRET_KEY
  tags:
    - k8s-stage
  allow_failure: true
