image: openjdk:11-jdk-slim

stages:
  - build
  - tests

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew
  - echo `pwd`

build:
  stage: build
  script:
    - ./gradlew assemble
  only:
    changes:
      - "*.gradle"
      - gradle.properties
  cache:
    key: gradle-cache-key
    paths:
      - .gradle/wrapper
      - .gradle/caches
    policy: push

cache:
  key: gradle-cache-key
  paths:
    - .gradle/wrapper
    - .gradle/caches
  policy: pull

CustomSuiteTestRun:
  when: manual
  image: gradle:jdk11
  stage: tests
  services:
    - selenium/standalone-chrome
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - echo $QASE
    - echo $BROWSER
    - cd web-tests
    - ./gradlew clean $TEST_SET -Penv=$P_ENV -Pbrowser=$BROWSER -Pqase=$QASE -Pkey=$ATST_APP_SECRET_KEY
    - wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.9.0/allure-commandline-2.9.0.tgz
    - tar -xvpf allure-commandline-2.9.0.tgz
    - ./allure-2.9.0/bin/allure generate --clean -o allure-reports build/allure-results
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
      - web-tests/logs/
      - web-tests/allure-reports/
    expire_in: 1 week

tests:ApiInstamart:
  when: manual
  resource_group: apiInstamart:$CI_COMMIT_REF_SLUG
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - cd web-tests
    - ./gradlew clean build apiInstamartRegress -Penv=$P_ENV -Pqase=true -Pkey=$ATST_APP_SECRET_KEY
  after_script:
    - cd web-tests
    - bash ./report.sh api-instamart-regress
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
      - web-tests/logs/
    expire_in: 1 week

tests:ApiShopper:
  when: manual
  resource_group: apiShopper:$CI_COMMIT_REF_SLUG
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - cd web-tests
    - ./gradlew clean build apiShopperRegress -Penv=$P_ENV -Pqase=true -Pkey=$ATST_APP_SECRET_KEY
  after_script:
    - cd web-tests
    - bash ./report.sh api-shopper-regress
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
      - web-tests/logs/
    expire_in: 1 week

tests:ApiZonesProductionOnly:
  when: manual
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - cd web-tests
    - ./gradlew clean build apiZones -Penv=$P_ENV -Pqase=true -Pkey=$ATST_APP_SECRET_KEY
  after_script:
    - cd web-tests
    - bash ./report.sh api-zones-production
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
      - web-tests/logs/
    expire_in: 1 week

tests:UiSmoke:
  when: manual
  stage: tests
  resource_group: uismoke:$CI_COMMIT_REF_SLUG
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - cd web-tests
    - ./gradlew clean build sberUiSmoke -Penv=$P_ENV -Pqase=true -Pkey=$ATST_APP_SECRET_KEY
  after_script:
    - cd web-tests
    - bash ./report.sh ui-stf-smoke
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
      - web-tests/logs/
    expire_in: 1 week

tests:AdminUiSmoke:
  when: manual
  stage: tests
  resource_group: uismoke:$CI_COMMIT_REF_SLUG
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - cd web-tests
    - ./gradlew clean build adminUiSmoke -Penv=$P_ENV -Pqase=true -Pkey=$ATST_APP_SECRET_KEY
  after_script:
    - cd web-tests
    - bash ./report.sh ui-admin-smoke
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
      - web-tests/logs/
    expire_in: 1 week

tests:AutoMRCheck:
  when: manual
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - cd web-tests
    - ./gradlew clean build AutoMRCheck -Penv=$P_ENV -Pqase=false -Pkey=$ATST_APP_SECRET_KEY
  after_script:
    - cd web-tests
    - bash ./report.sh default
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
      - web-tests/logs/
    expire_in: 1 week

tests:Debug:
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: manual
      allow_failure: true
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - cd web-tests
    - ./gradlew clean build debug -Penv=$P_ENV -Pqase=false -Pkey=$ATST_APP_SECRET_KEY
  after_script:
    - cd web-tests
    - bash ./report.sh debug
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
      - web-tests/logs/
    expire_in: 1 week
