image: gradle:jre11

variables:
  GIT_SUBMODULE_STRATEGY: normal
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  CI_RUN_ALL_JOBS: "true"

before_script:
  - cd web-tests

stages:
  - tests

.template_tests_apishopper:
  resource_group: apiShopper:$CI_COMMIT_REF_SLUG
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - gradle clean build apiShopperRegress -Penv=$P_ENV -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL -Purl_stf=$URL_STF -Purl_shp=$URL_SHP
  after_script:
    - cd web-tests
    - bash ./report.sh api api-shopper-regress
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/api/build/allure-results/
      - web-tests/api/logs/
    expire_in: 1 week

.template_tests_apishopper_alone:
  only:
    refs:
      - master
    variables:
      - $API_SHOPPER_ALONE == 'true' && $CI_RUN_ALL_JOBS == 'false'
  allow_failure: true

.template_run_all_jobs_at_a_time_on_master:
  only:
    refs:
      - master
    variables:
      - $CI_RUN_ALL_JOBS == 'true'
  allow_failure: true

CustomSuiteTestRun:
  when: manual
  stage: tests
  services:
    - selenium/standalone-chrome
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - echo $QASE
    - echo $BROWSER
    - echo $PROXY_IP
    - echo $PROXY_PORT
    - echo $PROXY_TIMEOUT
    - echo $URL_STF
    - echo $URL_SHP
    - gradle clean build $TEST_SET -Penv=$P_ENV -Pbrowser=$BROWSER -Pqase=$QASE -Pproxy_ip=$PROXY_IP -Pproxy_port=$PROXY_PORT -Pproxy_timeout=$PROXY_TIMEOUT -Pkey=$ATST_APP_SECRET_KEY -Purl_stf=$URL_STF -Purl_shp=$URL_SHP
    - wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.9.0/allure-commandline-2.9.0.tgz
    - tar -xvpf allure-commandline-2.9.0.tgz
    - ./allure-2.9.0/bin/allure generate --clean -o allure-reports build/allure-results
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
      - web-tests/logs/
      - web-tests/allure-reports/
    expire_in: 1 week

tests:ApiInstamart:
  extends: ".template_run_all_jobs_at_a_time_on_master"
  resource_group: apiInstamart:$CI_COMMIT_REF_SLUG
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - echo $URL_STF
    - echo $URL_SHP
    - if [ $URL_STF =~ ^stf-kraken ]; then $ALLURE_POSTFIX="preprod"; else $ALLURE_POSTFIX="staging"; fi
    - echo $ALLURE_POSTFIX
    - gradle clean build apiInstamartRegress -Penv=$P_ENV -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL -Purl_stf=$URL_STF -Purl_shp=$URL_SHP
  after_script:
    - cd web-tests
    - bash ./report.sh api api-instamart-$ALLURE_POSTFIX
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/api/build/allure-results/
      - web-tests/api/logs/
    expire_in: 1 week

tests:preprodApiMetro:
  when: manual
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - gradle clean build apiInstamartRegress -Penv=metro-preprod -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - cd web-tests
    - bash ./report.sh api api-metro-preprod
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/api/build/allure-results/
      - web-tests/api/logs/
    expire_in: 1 week

tests:prodApiInstamart:
  when: manual
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - gradle clean build apiInstamartProduction -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - cd web-tests
    - bash ./report.sh api api-instamart-production
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/api/build/allure-results/
      - web-tests/api/logs/
    expire_in: 1 week

tests:ApiShopper:
  extends:
    - ".template_tests_apishopper"
    - ".template_run_all_jobs_at_a_time_on_master"

tests:ApiShopper:alone:
  extends:
    - ".template_tests_apishopper"
    - ".template_tests_apishopper_alone"

tests:prodApiShopper:
  when: manual
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - gradle clean build apiShopperProduction -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - cd web-tests
    - bash ./report.sh api api-shopper-production
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/api/build/allure-results/
      - web-tests/api/logs/
    expire_in: 1 week

tests:prodApiZones:
  when: manual
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - gradle clean build apiZones -Penv=$P_ENV -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - cd web-tests
    - bash ./report.sh api api-zones-production
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/api/build/allure-results/
      - web-tests/api/logs/
    expire_in: 1 week

tests:prodApiRetailer:
  when: manual
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - gradle clean build apiRetailerE2E -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - cd web-tests
    - bash ./report.sh api api-retailer-e2e-production
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/api/build/allure-results/
      - web-tests/api/logs/
    expire_in: 1 week

tests:UiSmoke:
  extends: ".template_run_all_jobs_at_a_time_on_master"
  stage: tests
  resource_group: uismoke:$CI_COMMIT_REF_SLUG
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - echo $URL_STF
    - echo $URL_SHP
    - gradle clean build sberUiSmoke -Penv=$P_ENV -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL -Purl_stf=$URL_STF -Purl_shp=$URL_SHP
  after_script:
    - cd web-tests
    - bash ./report.sh ui ui-stf-smoke
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/ui/build/allure-results/
      - web-tests/ui/logs/
    expire_in: 1 week

tests:UiRegress:
  when: manual
  stage: tests
  resource_group: uiregress:$CI_COMMIT_REF_SLUG
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - echo $URL_STF
    - echo $URL_SHP
    - gradle clean build sberRegression -Penv=$P_ENV -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL -Purl_stf=$URL_STF -Purl_shp=$URL_SHP
  after_script:
    - cd web-tests
    - bash ./report.sh ui ui-stf-regress
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/ui/build/allure-results/
      - web-tests/ui/logs/
    expire_in: 1 week

tests:AdminUiSmoke:
  extends: ".template_run_all_jobs_at_a_time_on_master"
  stage: tests
  resource_group: uismoke:$CI_COMMIT_REF_SLUG
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - echo $URL_STF
    - echo $URL_SHP
    - gradle clean build adminUiSmoke -Penv=$P_ENV -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL -Purl_stf=$URL_STF -Purl_shp=$URL_SHP
  after_script:
    - cd web-tests
    - bash ./report.sh ui ui-admin-smoke
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/ui/build/allure-results/
      - web-tests/ui/logs/
    expire_in: 1 week

tests:prodUiSmoke:
  when: manual
  stage: tests
  resource_group: uismoke:$CI_COMMIT_REF_SLUG
  image: $CI_REGISTRY_IMAGE
  script:
    - gradle clean build uiSmokeProduction -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - cd web-tests
    - bash ./report.sh ui ui-smoke-production
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/ui/build/allure-results/
      - web-tests/ui/logs/
    expire_in: 1 week

tests:AutoMRCheck:
  only:
    - merge_requests
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - gradle clean build AutoMRCheck -Penv=$P_ENV -Pqase=false -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - cd web-tests
    - bash ./report.sh . default
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/api/build/allure-results/
      - web-tests/ui/build/allure-results/
      - web-tests/api/logs/
      - web-tests/ui/logs/
    expire_in: 1 week

tests:Debug:
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: manual
      allow_failure: true
  stage: tests
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - gradle clean build debug -Penv=$P_ENV -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - cd web-tests
    - bash ./report.sh debug
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
      - web-tests/logs/
    expire_in: 1 week
