testAuto:
  when: manual
  image: gradle:jdk11
  script:
    - cd web-tests
    - ./gradlew clean apiV2Regress -Penv=sbermarket-staging allureReport
  tags:
    - k8s-stage
  artifacts:
    paths:
      - web-tests/build/allure-results/
    expire_in: 1 week
