testAuto:
  when: manual
  image: selenoid/chrome
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - cd web-tests
    - ./gradlew clean sberSmoke -Penv=$P_ENV -Pbrowser=chrome allureReport
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
    expire_in: 1 week
