testAuto:
  when: manual
  image: gradle:jdk11
  script:
    - echo $P_ENV
    - echo $TEST_SET
    - cd web-tests
    - ./gradlew clean $TEST_SET -Penv=$P_ENV allureReport
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/build/allure-results/
    expire_in: 1 week
