tests:product:hub:
  resource_group: testProductHub
  only:
    variables:
      - $GRPC_PRODUCT_HUB_ALONE == 'true' && $CI_RUN_ALL_JOBS == 'false'
  extends:
    - ".template_grpc_tests"
  script:
    - gradle clean build grpcProductHub
  after_script:
    - bash ./report.sh grpc grpc-product-hub

tests:product:hub:schedule:
  resource_group: testProductHub
  extends:
    - ".template_grpc_tests"
    - ".template_schedule"
  stage: tests-api-service
  script:
    - gradle clean build grpcProductHub
  after_script:
    - bash ./report.sh grpc grpc-product-hub

tests:salut:token:
  resource_group: testSalutToken
  only:
    variables:
      - $GRPC_SALUT_TOKEN_ALONE == 'true' && $CI_RUN_ALL_JOBS == 'false'
  extends:
    - ".template_grpc_tests"
  script:
    - gradle clean build grpcSalutToken
  after_script:
    - bash ./report.sh grpc grpc-salut-token

tests:authorization:service:grpc:
  resource_group: testsAuthorizationServiceGRPC
  only:
    variables:
      - $GRPC_AUTHORIZATION_SERVER_ALONE == 'true' && $CI_RUN_ALL_JOBS == 'false'
  extends:
    - ".template_grpc_tests"
  script:
    - gradle clean build grpcAuthorizationService
  after_script:
    - bash ./report.sh grpc grpc-authorization-service
