tests:product:hub:
  resource_group: testProductHub
  extends:
    - ".template_grpc_tests"
    - ".template_run_schedule"
  script:
    - gradle clean build grpcProductHub -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - bash ./report.sh grpc grpc-product-hub

tests:salut:token:
  resource_group: testSalutToken
  only:
    variables:
      - $GRPC_SALUT_TOKEN_ALONE == 'true' && $CI_RUN_ALL_JOBS == 'false'
  extends:
    - ".template_grpc_tests"
  script:
    - gradle clean build grpcSalutToken -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - bash ./report.sh grpc grpc-salut-token
