tests:on:demand:shifts:
  resource_group: onDemandShifts
  extends:
    - ".template_api_tests"
  only:
    refs:
      - schedules
    variables:
      - $ON_DEMAND_SHIFTS == 'true'
  when: always
  script:
    - gradle clean build onDemandShifts
  after_script:
    - bash ./report.sh api on-demand-shifts

tests:on:demand:dispatch:
  resource_group: onDemandDispatch
  extends:
    - ".template_api_tests"
  only:
    refs:
      - schedules
    variables:
      - $ON_DEMAND_DISPATCH == 'true'
  when: always
  script:
    - gradle clean build onDemandDispatch
  after_script:
    - bash ./report.sh api on-demand-dispatch

tests:on:demand:workflow:
  resource_group: onDemandWorkflow
  extends:
    - ".template_api_tests"
  only:
    refs:
      - schedules
    variables:
      - $ON_DEMAND_WORKFLOW == 'true'
  when: always
  script:
    - gradle clean build onDemandWorkflow
  after_script:
    - bash ./report.sh api on-demand-workflow

tests:on:demand:eta:
  resource_group: onDemandETA
  extends:
    - ".template_api_tests"
  only:
    variables:
      - $ON_DEMAND_ETA == 'true'
  when: always
  script:
    - echo $URL_PAAS_ETA
    - gradle clean build onDemandETA -Purl_paas_eta=$URL_PAAS_ETA
  after_script:
    - bash ./mattermost-all-report.sh api on-demand-eta onDemandETA $MATTERMOST_HIGHGARDEN_KEY

tests:on:demand:tm:
  resource_group: onDemandTM
  extends:
    - ".template_grpc_tests"
  only:
    refs:
      - schedules
    variables:
      - $ON_DEMAND_TM == 'true'
  when: always
  script:
    - gradle clean build onDemandTM
  after_script:
    - bash ./mattermost-all-report.sh grpc on-demand-tm onDemandTM $MATTERMOST_HIGHGARDEN_KEY

tests:on:demand:shippingcalc:
  resource_group: onDemandShippingCalc
  extends:
    - ".template_api_tests"
  only:
    variables:
      - $ON_DEMAND_SHIPPINGCALC == 'true'
  when: always
  script:
    - echo $URL_PAAS_SHIPPINGCALC
    - gradle clean build onDemandShippingCalc -Purl_paas_shippingcalc=$URL_PAAS_SHIPPINGCALC
  after_script:
    - bash ./mattermost-all-report.sh api on-demand-shippingcalc onDemandShippingCalc $MATTERMOST_HIGHGARDEN_KEY

tests:on:demand:candidates:
  resource_group: onDemandCandidates
  extends:
    - ".template_api_tests"
  only:
    variables:
      - $ON_DEMAND_CANDIDATES == 'true'
  when: always
  script:
    - gradle clean build onDemandCandidates
  after_script:
    - bash ./report.sh api on-demand-candidates

tests:on:demand:surgelevel:
  resource_group: onDemandSurgeLevel
  extends:
    - ".template_api_tests"
  only:
    variables:
      - $ON_DEMAND_SURGELEVEL == 'true'
  when: always
  script:
    - echo $URL_PAAS_SURGELEVEL
    - gradle clean build onDemandSurgeLevel -Purl_paas_surgelevel=$URL_PAAS_SURGELEVEL
  after_script:
    - bash ./mattermost-all-report.sh api on-demand-surgelevel onDemandSurgeLevel $MATTERMOST_HIGHGARDEN_KEY