tests:on:demand:shifts:
  resource_group: onDemandShifts
  extends:
    - ".template_api_tests"
  only:
    variables:
      - $ON_DEMAND_SHIFTS == 'true'
  when: always
  script:
    - gradle clean build onDemandShifts
  after_script:
    - bash ./report.sh api on-demand-shifts
    - bash ./mattermost.sh api onDemandShifts $MATTERMOST_ONDEMAND_KEY false

tests:on:demand:dispatch:
  resource_group: onDemandDispatch
  extends:
    - ".template_api_tests"
  only:
    refs:
      - schedules
    variables:
      - $ON_DEMAND_DISPATCH == 'true'
  when: always
  script:
    - gradle clean build onDemandDispatch
  after_script:
    - bash ./report.sh api on-demand-dispatch
    - bash ./mattermost.sh api onDemandDispatch $MATTERMOST_ONDEMAND_KEY false

tests:on:demand:workflow:
  resource_group: onDemandWorkflow
  extends:
    - ".template_api_tests"
  only:
    refs:
      - schedules
    variables:
      - $ON_DEMAND_WORKFLOW == 'true'
  when: always
  script:
    - gradle clean build onDemandWorkflow
  after_script:
    - bash ./report.sh api on-demand-workflow
    - bash ./mattermost.sh api onDemandWorkflow $MATTERMOST_ONDEMAND_KEY false

tests:on:demand:eta:
  resource_group: onDemandETA
  extends:
    - ".template_api_tests"
  only:
    variables:
      - $ON_DEMAND_ETA == 'true'
  when: always
  script:
    - echo $URL_PAAS_ETA
    - gradle clean build onDemandETA -Purl_paas_eta=$URL_PAAS_ETA
  after_script:
    - bash ./report.sh api on-demand-eta
    - bash ./mattermost.sh api onDemandETA $MATTERMOST_HIGHGARDEN_KEY true
    - bash ./mattermost.sh api onDemandETA $MATTERMOST_ONDEMAND_KEY false

tests:on:demand:tm:
  resource_group: onDemandTM
  extends:
    - ".template_grpc_tests"
  only:
    refs:
      - schedules
    variables:
      - $ON_DEMAND_TM == 'true'
  when: always
  script:
    - gradle clean build onDemandTM
  after_script:
    - bash ./report.sh grpc on-demand-tm
    - bash ./mattermost.sh grpc onDemandTM $MATTERMOST_HIGHGARDEN_KEY true

tests:on:demand:shippingcalc:
  resource_group: onDemandShippingCalc
  extends:
    - ".template_api_tests"
  only:
    variables:
      - $ON_DEMAND_SHIPPINGCALC == 'true'
  when: always
  script:
    - echo $URL_PAAS_SHIPPINGCALC
    - gradle clean build onDemandShippingCalc -Purl_paas_shippingcalc=$URL_PAAS_SHIPPINGCALC
  after_script:
    - bash ./report.sh api on-demand-shippingcalc
    - bash ./mattermost.sh api onDemandShippingCalc $MATTERMOST_HIGHGARDEN_KEY true

tests:on:demand:candidates:
  resource_group: onDemandCandidates
  extends:
    - ".template_api_tests"
  only:
    variables:
      - $ON_DEMAND_CANDIDATES == 'true'
  when: always
  script:
    - gradle clean build onDemandCandidates
  after_script:
    - bash ./report.sh api on-demand-candidates
    - bash ./mattermost.sh api onDemandCandidates $MATTERMOST_ONDEMAND_KEY false

tests:on:demand:surgelevel:
  resource_group: onDemandSurgeLevel
  extends:
    - ".template_api_tests"
  only:
    variables:
      - $ON_DEMAND_SURGELEVEL == 'true'
  when: always
  script:
    - echo $SURGE_HASH_COMMIT_OR_BRANCH
    - gradle clean build onDemandSurgeLevel -Psurge_hash_commit_or_branch=$SURGE_HASH_COMMIT_OR_BRANCH
  after_script:
    - bash ./report.sh api on-demand-surgelevel
    - bash ./mattermost.sh api onDemandSurgeLevel $MATTERMOST_HIGHGARDEN_KEY true
    - bash ./mattermost.sh api onDemandSurgeLevel $MATTERMOST_ONDEMAND_KEY false

tests:on:demand:routeestimator:
  resource_group: onDemandRouteEstimator
  extends:
    - ".template_api_tests"
  only:
    variables:
      - $ON_DEMAND_ROUTEESTIMATOR == 'true'
  when: always
  script:
    - gradle clean build onDemandRes
  after_script:
    - bash ./report.sh api on-demand-route-estimator
    - bash ./mattermost.sh api onDemandRes $MATTERMOST_ONDEMAND_KEY false