tests:ApiShopper:
  only:
    variables:
      - $TEST_API_SHOPPER == 'true' && $CI_RUN_ALL_JOBS == 'false'
      - $CI_RUN_ALL_JOBS == 'true'
  extends:
    - ".template_tests_apishopper"
    - ".template_run_all_jobs_at_a_time_on_master"
  allow_failure: false

tests:ApiShopper:alone:
  extends:
    - ".template_tests_apishopper"
    - ".template_tests_apishopper_alone"
  allow_failure: false

tests:prodApiShopper:
  extends: ".template_run_all_jobs_at_a_time_on_master"
  resource_group: apiShopperProd
  when: manual
  stage: tests-api
  image: $CI_REGISTRY_IMAGE
  script:
    - gradle clean build apiShopperProduction -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - cd web-tests
    - bash ./report.sh api api-shopper-production
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/api/build/allure-results/
      - web-tests/api/logs/
      - web-tests/api/build/reports/tests/
    expire_in: 1 week
  allow_failure: false