tests:adminKeycloak:
  only:
    variables:
      - $RUN_KEYCLOAK == 'true' && $CI_RUN_ALL_JOBS == 'false'
  extends:
    - ".template_ui_tests"
  script:
    - gradle clean build adminKeycloak
  after_script:
    - bash ./report.sh reforged ui-stf-keycloak

tests:adminKeycloakProd:
  only:
    variables:
      - $RUN_KEYCLOAK_PROD == 'true' && $CI_RUN_ALL_JOBS == 'false'
  extends:
    - ".template_ui_tests"
  script:
    - gradle clean build adminKeycloakProd
  after_script:
    - bash ./report.sh reforged ui-stf-keycloak-prod

tests:adminOnDemandSmoke:
  only:
    variables:
      - $RUN_ON_DEMAND_ADMIN_SMOKE == 'true' && $CI_RUN_ALL_JOBS == 'false'
  extends:
    - ".template_ui_tests"
  script:
    - gradle clean build adminOnDemandSmoke
  after_script:
    - bash ./report.sh reforged admin-on-demand-smoke

tests:adminOnDemandRegress:
  only:
    variables:
      - $RUN_ON_DEMAND_ADMIN_REGRESS == 'true' && $CI_RUN_ALL_JOBS == 'false'
  extends:
    - ".template_ui_tests"
  script:
    - gradle clean build adminOnDemandRegress
  after_script:
    - bash ./report.sh reforged admin-on-demand-regress
