tests:metroRegression:
  extends:
    - ".template_ui_tests"
    - ".template_run_schedule"
  script:
    - gradle clean build metroRegression -Penv=metro-preprod -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - bash ./report.sh reforged ui-metro-preprod

tests:okeyRegression:
  extends:
    - ".template_ui_tests"
    - ".template_run_schedule"
  script:
    - gradle clean build okeyRegression -Penv=okey-preprod -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - bash ./report.sh reforged ui-okey-preprod

tests:selgrosRegression:
  extends:
    - ".template_ui_tests"
    - ".template_run_schedule"
  script:
    - gradle clean build selgrosRegression -Penv=selgros-preprod -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - bash ./report.sh reforged ui-selgros-preprod
