tests:selgrosSmoke:
  extends:
    - ".template_ui_tests"
    - ".template_schedule"
  stage: tests-ui-tenant
  script:
    - gradle clean build selgrosRegression
  after_script:
    - bash ./report.sh reforged ui-selgros-preprod

tests:businessRegression:
  extends:
    - ".template_ui_tests"
    - ".template_schedule"
  stage: tests-ui-tenant
  script:
    - gradle clean build businessRegression
  after_script:
    - bash ./report.sh reforged ui-business-preprod
