tests:metroSmoke:
  only:
    variables:
      - $TEST_API_INSTAMART == 'false' && $CI_RUN_ALL_JOBS == 'false' && $API_SHOPPER_ALONE == 'false'
  when: manual
  extends: ".template_ui_tests"
  script:
    - gradle clean build metroSmok -Penv=metro-preprod -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - bash ./report.sh reforged ui-metro-preprod

tests:okeySmoke:
  only:
    variables:
      - $TEST_API_INSTAMART == 'false' && $CI_RUN_ALL_JOBS == 'false' && $API_SHOPPER_ALONE == 'false'
  when: manual
  extends: ".template_ui_tests"
  script:
    - gradle clean build okeySmoke -Penv=okey-preprod -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - bash ./report.sh reforged ui-okey-preprod

tests:selgrosSmoke:
  only:
    variables:
      - $TEST_API_INSTAMART == 'false' && $CI_RUN_ALL_JOBS == 'false' && $API_SHOPPER_ALONE == 'false'
  when: manual
  extends: ".template_ui_tests"
  script:
    - gradle clean build selgrosSmoke -Penv=selgros-preprod -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - bash ./report.sh reforged ui-selgros-preprod