tests:selgrosSmoke:
  extends:
    - ".template_ui_tests"
    - ".template_schedule"
  stage: tests-ui-tenant
  script:
    - gradle clean build selgrosRegression -Penv=selgros-preprod -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - bash ./report.sh reforged ui-selgros-preprod

tests:businessRegression:
  extends:
    - ".template_ui_tests"
    - ".template_schedule"
  stage: tests-ui-tenant
  script:
    - gradle clean build businessRegression -Penv=business-preprod -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - bash ./report.sh reforged ui-business-preprod
