tests:UiSmoke:
  only:
    variables:
      - $TEST_UI_SMOKE == 'true' && $CI_RUN_ALL_JOBS == 'false'
      - $CI_RUN_ALL_JOBS == 'true'
  extends: ".template_run_all_jobs_at_a_time_on_master"
  stage: tests-ui
  needs:
    - "tests:ApiInstamart"
    - "tests:ApiShopper"
  resource_group: uismoke:$CI_COMMIT_REF_SLUG
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $URL_STF
    - echo $URL_SHP
    - gradle clean build sberUiSmoke -Penv=$P_ENV -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL -Purl_stf=$URL_STF -Purl_shp=$URL_SHP
  after_script:
    - cd web-tests
    - bash ./report.sh reforged ui-stf-smoke
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/reforged/build/allure-results/
      - web-tests/reforged/logs/
      - web-tests/reforged/build/reports/tests/
    expire_in: 1 week
  allow_failure: true

tests:UiRegress:
  extends: ".template_run_all_jobs_at_a_time_on_master"
  when: manual
  stage: tests-ui
  needs:
    - "tests:ApiInstamart"
    - "tests:ApiShopper"
  resource_group: uiregress:$CI_COMMIT_REF_SLUG
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $URL_STF
    - echo $URL_SHP
    - gradle clean build sberRegression -Penv=$P_ENV -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL -Purl_stf=$URL_STF -Purl_shp=$URL_SHP
  after_script:
    - cd web-tests
    - bash ./report.sh reforged ui-stf-regress
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/reforged/build/allure-results/
      - web-tests/reforged/logs/
      - web-tests/reforged/build/reports/tests/
    expire_in: 1 week
  allow_failure: true

tests:AdminUiSmoke:
  only:
    variables:
      - $TEST_ADMIN_UI_SMOKE == 'true' && $CI_RUN_ALL_JOBS == 'false'
      - $CI_RUN_ALL_JOBS == 'true'
  extends: ".template_run_all_jobs_at_a_time_on_master"
  stage: tests-ui
  needs:
    - "tests:ApiInstamart"
    - "tests:ApiShopper"
  resource_group: uismoke:$CI_COMMIT_REF_SLUG
  image: $CI_REGISTRY_IMAGE
  script:
    - echo $P_ENV
    - echo $URL_STF
    - echo $URL_SHP
    - gradle clean build adminUiSmoke -Penv=$P_ENV -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL -Purl_stf=$URL_STF -Purl_shp=$URL_SHP
  after_script:
    - cd web-tests
    - bash ./report.sh reforged ui-admin-smoke
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/reforged/build/allure-results/
      - web-tests/reforged/logs/
      - web-tests/reforged/build/reports/tests/
    expire_in: 1 week
  allow_failure: true

tests:prodUiSmoke:
  extends: ".template_run_all_jobs_at_a_time_on_master"
  when: manual
  stage: tests-ui
  needs:
    - "tests:ApiInstamart"
    - "tests:ApiShopper"
  resource_group: uismoke:$CI_COMMIT_REF_SLUG
  image: $CI_REGISTRY_IMAGE
  script:
    - gradle clean build uiSmokeProduction -Pqase=true -Pkey=$ATST_APP_SECRET_KEY -Ppip_url=$CI_PIPELINE_URL
  after_script:
    - cd web-tests
    - bash ./report.sh reforged ui-smoke-production
  tags:
    - k8s-stage
  artifacts:
    when: always
    paths:
      - web-tests/reforged/build/allure-results/
      - web-tests/reforged/logs/
      - web-tests/reforged/build/reports/tests/
    expire_in: 1 week
  allow_failure: true