tests:UiSmoke:
  only:
    variables:
      - $TEST_UI_SMOKE == 'true' && $CI_RUN_ALL_JOBS == 'false'
  extends:
    - ".template_ui_tests"
    - ".template_run_all_jobs_at_a_time_on_master"
  script:
    - gradle clean build sberUiSmoke
  after_script:
    - bash ./report.sh reforged ui-stf-smoke

tests:UiRegress:
  extends:
    - ".template_ui_tests"
    - ".template_schedule"
  needs:
    - "tests:ApiV1InstamartRegress"
    - "tests:ApiV2InstamartRegress"
    - "tests:ApiV3InstamartRegress"
  script:
    - gradle clean build sberRegression
  after_script:
    - bash ./report.sh reforged ui-stf-regress

tests:AdminUiSmoke:
  only:
    variables:
      - $TEST_ADMIN_UI_SMOKE == 'true' && $CI_RUN_ALL_JOBS == 'false'
  extends:
    - ".template_ui_tests"
    - ".template_run_all_jobs_at_a_time_on_master"
  stage: tests-ui-admin
  script:
    - gradle clean build adminUiSmoke
  after_script:
    - bash ./report.sh reforged ui-admin-smoke

tests:AdminUiRegress:
  extends:
    - ".template_ui_tests"
    - ".template_schedule"
  stage: tests-ui-admin
  needs:
    - "tests:ApiV1InstamartRegress"
    - "tests:ApiV2InstamartRegress"
    - "tests:ApiV3InstamartRegress"
  script:
    - gradle clean build adminUiRegress
  after_script:
    - bash ./report.sh reforged ui-admin-regress

tests:prodUiSmoke:
  only:
    refs:
      - schedules
    variables:
      - $STF_PROD_SMOKE == 'true'
  extends:
    - ".template_ui_tests"
  script:
    - gradle clean build uiSmokeProduction
  after_script:
   - bash ./report.sh reforged ui-smoke-production
   - bash ./mattermost.sh reforged uiSmokeProduction $MATTERMOST_KEY false

#tests:prodUiSmokeAdmin:
#  only:
#    variables:
#      - $ADMIN_PROD_SMOKE == 'true'
#  extends:
#    - ".template_ui_tests"
#    - ".template_prod"
#  script:
#    - gradle clean build uiAdminSmokeProduction
#  after_script:
#   - bash ./report.sh reforged ui-admin-smoke-production