version: '3'

services:
  selenoid:
    image: "aerokube/selenoid"
    volumes:
      - "$PWD/config:/etc/selenoid"
      - "$PWD/config/video:/opt/selenoid/video"
      - "$PWD/config/logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      OVERRIDE_VIDEO_OUTPUT_DIR: "$PWD/config/video"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-limit", "10"]
    network_mode: bridge
    ports:
      - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]