package ru.instamart.api.helper;

import com.google.protobuf.Duration;
import com.google.protobuf.Timestamp;
import com.google.protobuf.util.Timestamps;
import io.qameta.allure.Step;
import ru.instamart.api.model.v2.OrderV2;
import ru.instamart.jdbc.dao.stf.StoresDao;
import ru.instamart.kraken.config.EnvironmentProperties;
import ru.instamart.kraken.data.user.UserManager;
import workflow.ServiceGrpc;
import workflow.WorkflowEnums;
import workflow.WorkflowOuterClass;

import java.util.Date;

public class DispatchHelper {

    @Step("Подготавливаем запрос для создания маршрутного листа")
    public static WorkflowOuterClass.CreateWorkflowsRequest getWorkflowsRequest(OrderV2 order, String shipmentUuid, Timestamp time, WorkflowEnums.DeliveryType deliveryType) {
        return WorkflowOuterClass.CreateWorkflowsRequest
                .newBuilder()
                .addWorkflows(WorkflowOuterClass.Workflow.newBuilder()
                        .addAssignments(WorkflowOuterClass.Assignment.newBuilder()
                                .setPerformerUuid(UserManager.getDefaultShopper().getUuid())
                                .setSourceTypeValue(WorkflowEnums.SourceType.DISPATCH.getNumber())
                                .setPerformerVehicleValue(WorkflowEnums.PerformerVehicle.PEDESTRIAN_VALUE)
                                .setDeliveryTypeValue(deliveryType.getNumber())
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.ARRIVE_VALUE)
                                .setPosition(0)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid("6bc4dc40-37a0-45fe-ac7f-d4185c29da63")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.63533180125311)
                                        .setLon(37.62462253918757)
                                        .build())
                                .setPlanStartedAt(time)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.60166514312233)
                                        .setLon(37.62097454092305)
                                        .build())
                                .setPlanEndedAt(time)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.DELIVERY_VALUE)
                                .setPosition(2)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid("6bc4dc40-37a0-45fe-ac7f-d4185c29da63")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.63533180125311)
                                        .setLon(37.62462253918757)
                                        .build())
                                .setPlanStartedAt(time)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.60166514312233)
                                        .setLon(37.62097454092305)
                                        .build())
                                .setPlanEndedAt(time)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.PASS_TO_CLIENT_VALUE)
                                .setPosition(3)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid("6bc4dc40-37a0-45fe-ac7f-d4185c29da63")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.63533180125311)
                                        .setLon(37.62462253918757)
                                        .build())
                                .setPlanStartedAt(time)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.60166514312233)
                                        .setLon(37.62097454092305)
                                        .build())
                                .setPlanEndedAt(time)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .build())
                .build();
    }

    @Step("Подготавливаем запрос для создания маршрутного листа c разными параметрами")
    public static WorkflowOuterClass.CreateWorkflowsRequest getWorkflowsRequestWithDifferentParams(OrderV2 order, String shipmentUuid, OrderV2 secondOrder, String secondShipmentUuid, String parentUuid) {
        return WorkflowOuterClass.CreateWorkflowsRequest
                .newBuilder()
                .addWorkflows(WorkflowOuterClass.Workflow.newBuilder()
                        .addAssignments(WorkflowOuterClass.Assignment.newBuilder()
                                .setPerformerUuid(UserManager.getShp6Shopper2().getUuid())
                                .setSourceTypeValue(WorkflowEnums.SourceType.DISPATCH_VALUE)
                                .setPerformerVehicleValue(WorkflowEnums.PerformerVehicle.PEDESTRIAN_VALUE)
                                .setDeliveryTypeValue(WorkflowEnums.DeliveryType.DEFAULT_VALUE)
                                .setPostponedParentUuid(parentUuid)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.ARRIVE_VALUE)
                                .setPosition(0)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid("6bc4dc40-37a0-45fe-ac7f-d4185c29da63")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.63533180125311)
                                        .setLon(37.62462253918757)
                                        .build())
                                .setPlanStartedAt(Timestamps.MAX_VALUE)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.60166514312233)
                                        .setLon(37.62097454092305)
                                        .build())
                                .setPlanEndedAt(Timestamps.MAX_VALUE)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.DELIVERY_VALUE)
                                .setPosition(2)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(secondOrder.getShipments().get(0).getNumber())
                                        .setUuid(secondShipmentUuid)
                                        .setItemsCount(1520)
                                        .setItemsTotalAmount(1539.5f)
                                        .setWeightKg(12f)
                                        .setStoreUuid("6ac61a21-942b-47af-b07d-7b5fb7ffb8fa")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(56.63533180125311)
                                        .setLon(39.62462253918757)
                                        .build())
                                .setPlanStartedAt(Timestamps.fromDate(new Date()))
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(57.60166514312233)
                                        .setLon(39.62097454092305)
                                        .build())
                                .setPlanEndedAt(Timestamps.fromDate(new Date()))
                                .setDuration(Duration.newBuilder().setSeconds(12).build())
                                .setDistance(24L)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.PASS_TO_CLIENT_VALUE)
                                .setPosition(3)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(secondOrder.getShipments().get(0).getNumber())
                                        .setUuid(secondShipmentUuid)
                                        .setItemsCount(1502)
                                        .setItemsTotalAmount(2139.5f)
                                        .setWeightKg(11f)
                                        .setStoreUuid("6ac61a21-942b-47af-b07d-7b5fb7ffb8fa")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.63533180188311)
                                        .setLon(37.62462253918857)
                                        .build())
                                .setPlanStartedAt(Timestamps.fromDate(new Date()))
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.60166514312283)
                                        .setLon(37.62097454092308)
                                        .build())
                                .setPlanEndedAt(Timestamps.fromDate(new Date()))
                                .setDuration(Duration.newBuilder().setSeconds(14).build())
                                .setDistance(11L)
                                .build())
                        .build())
                .build();
    }

    @Step("Подготавливаем запрос для создания маршрутного листа c транспортом {transportType}")
    public static WorkflowOuterClass.CreateWorkflowsRequest getWorkflowsRequestWithTransport(OrderV2 order, String shipmentUuid, long transportId, WorkflowOuterClass.Shift.Transport transportType) {
        return WorkflowOuterClass.CreateWorkflowsRequest
                .newBuilder()
                .addWorkflows(WorkflowOuterClass.Workflow.newBuilder()
                        .addAssignments(WorkflowOuterClass.Assignment.newBuilder()
                                .setPerformerUuid(UserManager.getDefaultShopper().getUuid())
                                .setSourceTypeValue(WorkflowEnums.SourceType.DISPATCH.getNumber())
                                .setPerformerVehicleValue(WorkflowEnums.PerformerVehicle.PEDESTRIAN_VALUE)
                                .setDeliveryTypeValue(WorkflowEnums.DeliveryType.DEFAULT_VALUE)
                                .setShift(WorkflowOuterClass.Shift.newBuilder()
                                        .setId(transportId)
                                        .setTransport(transportType)
                                        .build())
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.ARRIVE_VALUE)
                                .setPosition(0)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid("6bc4dc40-37a0-45fe-ac7f-d4185c29da63")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.63533180125311)
                                        .setLon(37.62462253918757)
                                        .build())
                                .setPlanStartedAt(Timestamps.MAX_VALUE)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.60166514312233)
                                        .setLon(37.62097454092305)
                                        .build())
                                .setPlanEndedAt(Timestamps.MAX_VALUE)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.DELIVERY_VALUE)
                                .setPosition(2)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid("6bc4dc40-37a0-45fe-ac7f-d4185c29da63")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.63533180125311)
                                        .setLon(37.62462253918757)
                                        .build())
                                .setPlanStartedAt(Timestamps.MAX_VALUE)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.60166514312233)
                                        .setLon(37.62097454092305)
                                        .build())
                                .setPlanEndedAt(Timestamps.MAX_VALUE)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.PASS_TO_CLIENT_VALUE)
                                .setPosition(3)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid("6bc4dc40-37a0-45fe-ac7f-d4185c29da63")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.63533180125311)
                                        .setLon(37.62462253918757)
                                        .build())
                                .setPlanStartedAt(Timestamps.MAX_VALUE)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.60166514312233)
                                        .setLon(37.62097454092305)
                                        .build())
                                .setPlanEndedAt(Timestamps.MAX_VALUE)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .build())
                .build();
    }

    @Step("Подготавливаем запрос для создания маршрутного листа c разными магазинами в сегментах")
    public static WorkflowOuterClass.CreateWorkflowsRequest getWorkflowsRequestWithDifferentStores(OrderV2 order, String shipmentUuid) {
        return  WorkflowOuterClass.CreateWorkflowsRequest
                .newBuilder()
                .addWorkflows(WorkflowOuterClass.Workflow.newBuilder()
                        .addAssignments(WorkflowOuterClass.Assignment.newBuilder()
                                .setPerformerUuid(UserManager.getDefaultShopper().getUuid())
                                .setSourceTypeValue(WorkflowEnums.SourceType.DISPATCH.getNumber())
                                .setPerformerVehicleValue(WorkflowEnums.PerformerVehicle.PEDESTRIAN_VALUE)
                                .setDeliveryTypeValue(WorkflowEnums.DeliveryType.DEFAULT_VALUE)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.ARRIVE_VALUE)
                                .setPosition(0)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid("6bc4dc40-37a0-45fe-ac7f-d4185c29da63")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.63533180125311)
                                        .setLon(37.62462253918757)
                                        .build())
                                .setPlanStartedAt(Timestamps.MAX_VALUE)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.60166514312233)
                                        .setLon(37.62097454092305)
                                        .build())
                                .setPlanEndedAt(Timestamps.MAX_VALUE)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.DELIVERY_VALUE)
                                .setPosition(2)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid(StoresDao.INSTANCE.findById(EnvironmentProperties.DEFAULT_SID).get().getUuid())
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.63533180125311)
                                        .setLon(37.62462253918757)
                                        .build())
                                .setPlanStartedAt(Timestamps.MAX_VALUE)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.60166514312233)
                                        .setLon(37.62097454092305)
                                        .build())
                                .setPlanEndedAt(Timestamps.MAX_VALUE)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.PASS_TO_CLIENT_VALUE)
                                .setPosition(3)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid(StoresDao.INSTANCE.findById(EnvironmentProperties.DEFAULT_METRO_MOSCOW_SID).get().getUuid())
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.63533180125311)
                                        .setLon(37.62462253918757)
                                        .build())
                                .setPlanStartedAt(Timestamps.MAX_VALUE)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(55.60166514312233)
                                        .setLon(37.62097454092305)
                                        .build())
                                .setPlanEndedAt(Timestamps.MAX_VALUE)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .build())
                .build();
    }



    @Step("Отменяем маршрутный лист")
    public static void cancelWorkflow(ServiceGrpc.ServiceBlockingStub clientWorkflow, String shipmentUuid) {
        var request = WorkflowOuterClass.RejectWorkflowByShipmentUuidRequest
                .newBuilder()
                .setShipmentUuid(shipmentUuid)
                .build();

        var response = clientWorkflow.rejectWorkflowByShipmentUUID(request);
    }
}
