package ru.instamart.api.helper;

import com.google.protobuf.Duration;
import com.google.protobuf.Timestamp;
import com.google.protobuf.util.Timestamps;
import io.qameta.allure.Step;
import io.restassured.response.Response;
import ru.instamart.api.enums.SessionType;
import ru.instamart.api.factory.SessionFactory;
import ru.instamart.api.model.v2.OrderV2;
import ru.instamart.api.model.workflows.ShopperAssignment;
import ru.instamart.api.request.workflows.AssignmentsRequest;
import ru.instamart.jdbc.dao.stf.StoresDao;
import ru.instamart.kraken.config.EnvironmentProperties;
import ru.instamart.kraken.data.StartPointsTenants;
import ru.instamart.kraken.data.user.UserData;
import ru.instamart.kraken.data.user.UserManager;
import workflow.ServiceGrpc;
import workflow.WorkflowEnums;
import workflow.WorkflowOuterClass;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

import static ru.instamart.api.checkpoint.StatusCodeCheckpoints.checkStatusCode200;
import static ru.instamart.kraken.data.StartPointsTenants.METRO_WORKFLOW_END;
import static ru.instamart.kraken.data.StartPointsTenants.METRO_WORKFLOW_START;

public class WorkflowHelper {

    private static final UserData secondShopper = UserManager.getShp6Shopper2();

    @Step("Подготавливаем запрос для создания маршрутного листа")
    public static WorkflowOuterClass.CreateWorkflowsRequest getWorkflowsRequest(OrderV2 order, String shipmentUuid, Timestamp time, WorkflowEnums.DeliveryType deliveryType) {
        return WorkflowOuterClass.CreateWorkflowsRequest
                .newBuilder()
                .addWorkflows(WorkflowOuterClass.Workflow.newBuilder()
                        .addAssignments(WorkflowOuterClass.Assignment.newBuilder()
                                .setPerformerUuid(SessionFactory.getSession(SessionType.SHOPPER_APP).getUserData().getUuid())
                                .setSourceTypeValue(WorkflowEnums.SourceType.DISPATCH.getNumber())
                                .setPerformerVehicleValue(WorkflowEnums.PerformerVehicle.PEDESTRIAN_VALUE)
                                .setDeliveryTypeValue(deliveryType.getNumber())
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.ARRIVE_VALUE)
                                .setPosition(0)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid("6bc4dc40-37a0-45fe-ac7f-d4185c29da63")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_START.getLat())
                                        .setLon(METRO_WORKFLOW_START.getLon())
                                        .build())
                                .setPlanStartedAt(time)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_END.getLat())
                                        .setLon(METRO_WORKFLOW_END.getLon())
                                        .build())
                                .setPlanEndedAt(time)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.DELIVERY_VALUE)
                                .setPosition(2)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid("6bc4dc40-37a0-45fe-ac7f-d4185c29da63")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_START.getLat())
                                        .setLon(METRO_WORKFLOW_START.getLon())
                                        .build())
                                .setPlanStartedAt(time)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_END.getLat())
                                        .setLon(METRO_WORKFLOW_END.getLon())
                                        .build())
                                .setPlanEndedAt(time)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.PASS_TO_CLIENT_VALUE)
                                .setPosition(3)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid("6bc4dc40-37a0-45fe-ac7f-d4185c29da63")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_START.getLat())
                                        .setLon(METRO_WORKFLOW_START.getLon())
                                        .build())
                                .setPlanStartedAt(time)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_END.getLat())
                                        .setLon(METRO_WORKFLOW_END.getLon())
                                        .build())
                                .setPlanEndedAt(time)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .build())
                .build();
    }

    @Step("Подготавливаем запрос для создания маршрутного листа c разными параметрами")
    public static WorkflowOuterClass.CreateWorkflowsRequest getWorkflowsRequestWithDifferentParams(OrderV2 order, String shipmentUuid, OrderV2 secondOrder, String secondShipmentUuid, String parentUuid) {
        return WorkflowOuterClass.CreateWorkflowsRequest
                .newBuilder()
                .addWorkflows(WorkflowOuterClass.Workflow.newBuilder()
                        .addAssignments(WorkflowOuterClass.Assignment.newBuilder()
                                .setPerformerUuid(secondShopper.getUuid())
                                .setSourceTypeValue(WorkflowEnums.SourceType.DISPATCH_VALUE)
                                .setPerformerVehicleValue(WorkflowEnums.PerformerVehicle.PEDESTRIAN_VALUE)
                                .setDeliveryTypeValue(WorkflowEnums.DeliveryType.DEFAULT_VALUE)
                                .setPostponedParentUuid(parentUuid)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.ARRIVE_VALUE)
                                .setPosition(0)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid("6bc4dc40-37a0-45fe-ac7f-d4185c29da63")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_START.getLat())
                                        .setLon(METRO_WORKFLOW_START.getLon())
                                        .build())
                                .setPlanStartedAt(Timestamps.MAX_VALUE)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_END.getLat())
                                        .setLon(METRO_WORKFLOW_END.getLon())
                                        .build())
                                .setPlanEndedAt(Timestamps.MAX_VALUE)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.DELIVERY_VALUE)
                                .setPosition(2)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(secondOrder.getShipments().get(0).getNumber())
                                        .setUuid(secondShipmentUuid)
                                        .setItemsCount(1520)
                                        .setItemsTotalAmount(1539.5f)
                                        .setWeightKg(12f)
                                        .setStoreUuid("6ac61a21-942b-47af-b07d-7b5fb7ffb8fa")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_START.getLat())
                                        .setLon(METRO_WORKFLOW_START.getLon())
                                        .build())
                                .setPlanStartedAt(Timestamps.fromDate(new Date()))
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_END.getLat())
                                        .setLon(METRO_WORKFLOW_END.getLon())
                                        .build())
                                .setPlanEndedAt(Timestamps.fromDate(new Date()))
                                .setDuration(Duration.newBuilder().setSeconds(12).build())
                                .setDistance(24L)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.PASS_TO_CLIENT_VALUE)
                                .setPosition(3)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(secondOrder.getShipments().get(0).getNumber())
                                        .setUuid(secondShipmentUuid)
                                        .setItemsCount(1502)
                                        .setItemsTotalAmount(2139.5f)
                                        .setWeightKg(11f)
                                        .setStoreUuid("6ac61a21-942b-47af-b07d-7b5fb7ffb8fa")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_START.getLat())
                                        .setLon(METRO_WORKFLOW_START.getLon())
                                        .build())
                                .setPlanStartedAt(Timestamps.fromDate(new Date()))
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_END.getLat())
                                        .setLon(METRO_WORKFLOW_END.getLon())
                                        .build())
                                .setPlanEndedAt(Timestamps.fromDate(new Date()))
                                .setDuration(Duration.newBuilder().setSeconds(14).build())
                                .setDistance(11L)
                                .build())
                        .build())
                .build();
    }

    @Step("Подготавливаем запрос для создания маршрутного листа c транспортом {transportType}")
    public static WorkflowOuterClass.CreateWorkflowsRequest getWorkflowsRequestWithTransport(OrderV2 order, String shipmentUuid, long transportId, WorkflowOuterClass.Shift.Transport transportType) {
        return WorkflowOuterClass.CreateWorkflowsRequest
                .newBuilder()
                .addWorkflows(WorkflowOuterClass.Workflow.newBuilder()
                        .addAssignments(WorkflowOuterClass.Assignment.newBuilder()
                                .setPerformerUuid(SessionFactory.getSession(SessionType.SHOPPER_APP).getUserData().getUuid())
                                .setSourceTypeValue(WorkflowEnums.SourceType.DISPATCH.getNumber())
                                .setPerformerVehicleValue(WorkflowEnums.PerformerVehicle.PEDESTRIAN_VALUE)
                                .setDeliveryTypeValue(WorkflowEnums.DeliveryType.DEFAULT_VALUE)
                                .setShift(WorkflowOuterClass.Shift.newBuilder()
                                        .setId(transportId)
                                        .setTransport(transportType)
                                        .build())
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.ARRIVE_VALUE)
                                .setPosition(0)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid("6bc4dc40-37a0-45fe-ac7f-d4185c29da63")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_START.getLat())
                                        .setLon(METRO_WORKFLOW_START.getLon())
                                        .build())
                                .setPlanStartedAt(Timestamps.MAX_VALUE)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_END.getLat())
                                        .setLon(METRO_WORKFLOW_END.getLon())
                                        .build())
                                .setPlanEndedAt(Timestamps.MAX_VALUE)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.DELIVERY_VALUE)
                                .setPosition(2)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid("6bc4dc40-37a0-45fe-ac7f-d4185c29da63")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_START.getLat())
                                        .setLon(METRO_WORKFLOW_START.getLon())
                                        .build())
                                .setPlanStartedAt(Timestamps.MAX_VALUE)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_END.getLat())
                                        .setLon(METRO_WORKFLOW_END.getLon())
                                        .build())
                                .setPlanEndedAt(Timestamps.MAX_VALUE)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.PASS_TO_CLIENT_VALUE)
                                .setPosition(3)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid("6bc4dc40-37a0-45fe-ac7f-d4185c29da63")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .setStoreName("METRO, Дорожная")
                                        .setStoreAddress("Москва, Дорожная,  д. 1, корп. 1")
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_START.getLat())
                                        .setLon(METRO_WORKFLOW_START.getLon())
                                        .build())
                                .setPlanStartedAt(Timestamps.MAX_VALUE)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_END.getLat())
                                        .setLon(METRO_WORKFLOW_END.getLon())
                                        .build())
                                .setPlanEndedAt(Timestamps.MAX_VALUE)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .build())
                .build();
    }

    @Step("Подготавливаем запрос для создания маршрутного листа c разными магазинами в сегментах")
    public static WorkflowOuterClass.CreateWorkflowsRequest getWorkflowsRequestWithDifferentStores(OrderV2 order, String shipmentUuid, String performerUuid) {
        return WorkflowOuterClass.CreateWorkflowsRequest
                .newBuilder()
                .addWorkflows(WorkflowOuterClass.Workflow.newBuilder()
                        .addAssignments(WorkflowOuterClass.Assignment.newBuilder()
                                .setPerformerUuid(performerUuid)
                                .setSourceTypeValue(WorkflowEnums.SourceType.DISPATCH.getNumber())
                                .setPerformerVehicleValue(WorkflowEnums.PerformerVehicle.PEDESTRIAN_VALUE)
                                .setDeliveryTypeValue(WorkflowEnums.DeliveryType.DEFAULT_VALUE)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.ARRIVE_VALUE)
                                .setPosition(0)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid("6bc4dc40-37a0-45fe-ac7f-d4185c29da63")
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_START.getLat())
                                        .setLon(METRO_WORKFLOW_START.getLon())
                                        .build())
                                .setPlanStartedAt(Timestamps.MAX_VALUE)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_END.getLat())
                                        .setLon(METRO_WORKFLOW_END.getLon())
                                        .build())
                                .setPlanEndedAt(Timestamps.MAX_VALUE)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.DELIVERY_VALUE)
                                .setPosition(2)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid(StoresDao.INSTANCE.findById(EnvironmentProperties.DEFAULT_SID).get().getUuid())
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_START.getLat())
                                        .setLon(METRO_WORKFLOW_START.getLon())
                                        .build())
                                .setPlanStartedAt(Timestamps.MAX_VALUE)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_END.getLat())
                                        .setLon(METRO_WORKFLOW_END.getLon())
                                        .build())
                                .setPlanEndedAt(Timestamps.MAX_VALUE)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .addSegments(WorkflowOuterClass.Segment.newBuilder()
                                .setTypeValue(WorkflowEnums.SegmentType.PASS_TO_CLIENT_VALUE)
                                .setPosition(3)
                                .addShipments(WorkflowEnums.Shipment.newBuilder()
                                        .setNumber(order.getShipments().get(0).getNumber())
                                        .setUuid(shipmentUuid)
                                        .setItemsCount(1500)
                                        .setItemsTotalAmount(2539.5f)
                                        .setWeightKg(10f)
                                        .setStoreUuid(StoresDao.INSTANCE.findById(EnvironmentProperties.DEFAULT_METRO_MOSCOW_SID).get().getUuid())
                                        .setIsHeavy(false)
                                        .setIsNew(false)
                                        .build())
                                .setLocationStart(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_START.getLat())
                                        .setLon(METRO_WORKFLOW_START.getLon())
                                        .build())
                                .setPlanStartedAt(Timestamps.MAX_VALUE)
                                .setLocationEnd(WorkflowEnums.Location.newBuilder()
                                        .setLat(METRO_WORKFLOW_END.getLat())
                                        .setLon(METRO_WORKFLOW_END.getLon())
                                        .build())
                                .setPlanEndedAt(Timestamps.MAX_VALUE)
                                .setDuration(Duration.newBuilder().setSeconds(10).build())
                                .setDistance(25L)
                                .build())
                        .build())
                .build();
    }


    @Step("Отменяем маршрутный лист")
    public static void cancelWorkflow(ServiceGrpc.ServiceBlockingStub clientWorkflow, String shipmentUuid) {
        var request = WorkflowOuterClass.RejectWorkflowByShipmentUuidRequest
                .newBuilder()
                .setShipmentUuid(shipmentUuid)
                .build();

        var response = clientWorkflow.rejectWorkflowByShipmentUUID(request);
    }

    @Step("Берем в работу маршрутный лист")
    public static void acceptWorkflow(String assignmentId) {
        final Response response = AssignmentsRequest.Accept.PATCH(assignmentId);
        checkStatusCode200(response);
    }

    @Step("Берем в работу маршрутный лист и начинаем маршрут")
    public static void acceptWorkflowAndStart(String assignmentId, StartPointsTenants coordinates) {
        final Response response = AssignmentsRequest.Accept.PATCH(assignmentId, coordinates);
        checkStatusCode200(response);
    }

    @Step("Создаем маршрутный лист")
    public static String getWorkflowUuid(OrderV2 order, String shipmentUuid, Timestamp timestamp, ServiceGrpc.ServiceBlockingStub clientWorkflow) {
        var request = getWorkflowsRequest(order, shipmentUuid, timestamp, WorkflowEnums.DeliveryType.DEFAULT);
        var response = clientWorkflow.createWorkflows(request);
        return response.getResultsMap().keySet().toArray()[0].toString();
    }

    @Step("Получаем список маршрутных листов шоппера")
    public static List<ShopperAssignment> getShopperAssignments() {
        final Response response = AssignmentsRequest.GET();
        checkStatusCode200(response);
        return Arrays.asList(response.as(ShopperAssignment[].class));
    }
}
